# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Event.create([{ name: 'Gamers assembly', subtitle: 'Saison 2018', start: '2018-06-23', end: '2018-06-23', category_id: '7', fav: '1', event_br: '1', event_classic: '0', event_special: '0', description: 'Donec maximus dolor tortor, vitae semper eros auctor et.', logo: '#', image: 'http://image.noelshack.com/fichiers/2018/21/2/1526989901-esport3.png' }])
Event.create([{ name: 'Dreamhack Tours', subtitle: 'Saison 2017', start: '2018-06-23', end: '2018-06-23', category_id: '2', fav: '0', event_br: '0', event_classic: '1', event_special: '0', description: 'Donec maximus dolor tortor, vitae semper eros auctor et.', logo: '#', image: 'http://image.noelshack.com/fichiers/2018/21/2/1526989901-esport3.png' }])
Event.create([{ name: 'ZrT CUP 2018', subtitle: 'Invitationnal 2018', start: '2018-06-23', end: '2018-06-23', category_id: '3', fav: '0', event_br: '0', event_classic: '0', event_special: '1', description: 'Donec maximus dolor tortor, vitae semper eros auctor et.', logo: '#', image: 'http://image.noelshack.com/fichiers/2018/21/2/1526989901-esport3.png' }])
Event.create([{ name: 'Dreamhack Marseille', subtitle: 'Saison 2018', start: '2018-06-23', end: '2018-06-23', category_id: '4', fav: '1', event_br: '0', event_classic: '1', event_special: '0', description: 'Donec maximus dolor tortor, vitae semper eros auctor et.', logo: '#', image: 'http://image.noelshack.com/fichiers/2018/21/2/1526989901-esport3.png' }])
Event.create([{ name: 'Paris Games Week', subtitle: 'Invitationnal 2017', start: '2018-06-23', end: '2018-06-23', category_id: '5', fav: '1', event_br: '0', event_classic: '0', event_special: '1', description: 'Donec maximus dolor tortor, vitae semper eros auctor et.', logo: '#', image: 'http://image.noelshack.com/fichiers/2018/21/2/1526989901-esport3.png' }])
Event.create([{ name: 'ESL PGI Cup', subtitle: 'Saison 2018', start: '2018-06-23', end: '2018-06-23', category_id: '1', fav: '1', event_br: '1', event_classic: '0', event_special: '0', description: 'Donec maximus dolor tortor, vitae semper eros auctor et.', logo: '#', image: 'http://image.noelshack.com/fichiers/2018/21/2/1526989901-esport3.png' }])
Game.create([{ name: 'GAME1LDLCvsFNATICDHTours', gamestart_tw: '262536885', match_id: '1', gamestart_yt: '', namestream: 'ZeRaToR', urlstream: '#' }])
Game.create([{ name: 'GAME2LDLCvsFNATICDHTours', gamestart_yt: 'JtS37z7g8cw', match_id: '1', gamestart_tw: '', namestream: 'ZeRaToR', urlstream: '#' }])
Game.create([{ name: 'GAME3LDLCvsFNATICDHTours', gamestart_yt: 'Ad22UNQKfpY', match_id: '1', gamestart_tw: '', namestream: 'ZeRaToR', urlstream: '#' }])
Game.create([{ name: 'GAME4LDLCvsFNATICDHTours', gamestart_tw: '263708484', match_id: '1', gamestart_yt: '', namestream: 'ZeRaToR', urlstream: '#' }])
Match.create([{ name: 'LDLCvsFNATIC20-10-2018DHTours', day: 'Quart de final', group: 'Playoffs', bestof: '03', team1: '1', team2: '2', event_id: '4', spoil: '0' }])
Match.create([{ name: 'MOUSEESPORTvsFAZECLAN22-10-2018GA', day: 'Jour 02', group: 'Groupe B', bestof: '05', team1: '3', team2: '4', event_id: '4', spoil: '1' }])
Category.create([{ name: 'Fortnite', slug: 'fortnite' }])
Category.create([{ name: 'Starcraft 2', slug: 'starcraft-2' }])
Category.create([{ name: 'PUBG', slug: 'pubg' }])
Category.create([{ name: 'CS:GO', slug: 'cs-go' }])
Category.create([{ name: 'Darwin Project', slug: 'darwin-project' }])
Category.create([{ name: 'Rocket League', slug: 'rocket-league' }])
Category.create([{ name: 'League of Legends', slug: 'league-of-legends' }])
Category.create([{ name: 'Heroes of the Storm', slug: 'heroes-of-the-storm' }])
Category.create([{ name: 'Overwatch', slug: 'overwatch' }])
Category.create([{ name: 'Autres', slug: 'autres' }])
Category.create([{ name: 'Battlerite', slug: 'battlerite' }])
Category.create([{ name: 'DOTA 2', slug: 'dota-2' }])
Team.create([{ name: 'LDLC', logo: '#' }])
Team.create([{ name: 'FAZE Clan', logo: '#' }])
Team.create([{ name: 'Fnatic', logo: '#' }])
Team.create([{ name: 'MouseEsport', logo: '#' }])
Support.create([{ name: 'ZeRaToR', subtitle: 'Streamer', link: '#', logo: '#' }])
Support.create([{ name: 'Momanus', subtitle: 'Streamer', link: '#', logo: '#' }])
Support.create([{ name: 'Team aAa', subtitle: 'Actualités', link: '#', logo: '#' }])
Article.create([{ title: 'Bienvenue sur le site', link: '#', image: 'http://image.noelshack.com/fichiers/2018/21/2/1526984709-esport.jpeg', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in risus quam. Pellentesque vel sapien at sapien tincidunt sollicitudin. Integer dui nunc, tristique a ligula a, ultrices vehicula diam. Suspendisse potenti. Cras in velit felis. Praesent a elit ac purus gravida laoreet. Nunc pretium sit amet nunc vitae congue.' }])
